# Generated by Django 5.0.4 on 2024-11-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_day', models.IntegerField()),
                ('fitness_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fitnessuser')),
            ],
        ),
    ]
