# Generated by Django 5.0.4 on 2024-11-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appoinment_date',
            new_name='appointment_date',
        ),
    ]
