# Generated by Django 5.0.4 on 2024-11-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRountine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fitnessuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('workout_routine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutrountine')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('fitness_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fitnessuser')),
                ('workout_routine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutrountine')),
            ],
        ),
    ]
