# Generated by Django 5.0.4 on 2024-11-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutRountine',
            new_name='WorkoutRoutine',
        ),
    ]
