# Generated by Django 5.0.4 on 2024-11-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('medical_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
    ]
